spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///db1   #///表示localhost
  redis:
    port: 6379
    host: localhost
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印mybatis执行的sql语句
#  mapper-locations: classpath:/mapper/*.xml
